'use client'
import Image from 'next/image'
import boy from '@/public/images/boy.jpg'
import { Metadata } from 'next'
import { useState } from 'react'
// import HeavyComponent from './components/HeavyComponent'
import dynamic from 'next/dynamic'
// const HeavyComponent = dynamic(() => import('./components/HeavyComponent'), {
//   loading: () => <div>Loading...</div>,
//   ssr: false,
// })
// import _ from 'lodash'

export default function Home() {
  // const [isVisible, setVisible] = useState(false)
  return (
    <main className='relative h-screen'>
      <h1>Hello World</h1>
      <button onClick={async () => {
        const _ =(await import ('lodash')).default
        const users = [
          { 'name': 'c' },
          { 'name': 'b' },
          { 'name': 'a' },
        ]
       const sorted = _.orderBy(users, ['name'])
       console.log(sorted)
      }}>Show</button>
      {/* <Image src={boy} alt='Boy' />*/}
      {/* <Image src="https://bit.ly/react-cover" alt='Boy' width={300} height={170} /> */}
      {/* <Image src="https://bit.ly/react-cover" alt='Boy' fill style={{ objectFit: 'cover' }} /> */}
      {/* <Image src="https://bit.ly/react-cover" alt='Boy' fill className="object-cover" sizes="(max-width: 470px) 100vw, (max-width: 768px) 50vw, 33vw" /> */}
      {/* <Image src="https://bit.ly/react-cover" alt='Boy' fill className="object-cover" sizes="(max-width: 470px) 100vw, (max-width: 768px) 50vw, 33vw" quality={100} /> */}
      {/* <Image 
        src="https://bit.ly/react-cover"
        alt='Boy'
        fill
        className="object-cover"
        sizes="(max-width: 470px) 100vw, (max-width: 768px) 50vw, 33vw"
        quality={100}
        priority /> */}
    </main>
  )
}

// export const metadata: Metadata = {
//   title: 'Home - Create Next App',
//   description: 'Generated by create next app',
// }

// export async function generateMetadata(): Promise<Metadata> {
//   return {
//     title: 'Home Pro - Create Next App',
//     description: 'Generated by create next app',
//   }
// }
